MACOSX_SDK_VERSION:       # [osx and x86_64]
  - 10.15                 # [osx and x86_64]
CONDA_BUILD_SYSROOT:      # [osx and x86_64]
  - /opt/MacOSX10.15.sdk  # [osx and x86_64]
macos_min_version:
  - 10.15  # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:
  - 10.15  # [osx and x86_64]