{% set version = "2.0.17.1" %}

package:
  name: uwsgi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uWSGI/uwsgi-{{ version }}.tar.gz
  sha256: d2318235c74665a60021a4fc7770e9c2756f9fc07de7b8c22805efe85b5ab277

build:
  number: 1
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - jansson
    - libxml2  # [not win]
    - openssl
    - pcre
    - yaml
    - zlib
  run:
    - python
    - jansson
    - libxml2  # [not win]
    - openssl
    - pcre
    - yaml
    - zlib

test:
  source_files:
    - .
  commands:
    - uwsgi --version
    - uwsgi --plugin-list
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/unbit/uwsgi
  license: GPL-2.0
  license_file: LICENSE
  summary: |
    The uWSGI project aims at developing a full stack for building hosting
    services. Application servers (for various programming languages and
    protocols), proxies, process managers and monitors are all implemented.

extra:
  recipe-maintainers:
    - kalefranz
    - ocefpaf
