travis:
  secure:
    BINSTAR_TOKEN: FEA6eZ2yOvk3weGjscGrajRH/W+Qi7/RZ929g/d8UkO66mFQgvAoNr48t22qc5Wodr//0zXr73TJFHOaN5WTBeLicI6QFOtZO7VNh8Ji6kMvAd97Mw2C3GfrzLqMtuMV2KxdorolYM6F7oVjAfS+kMbK0xqq3LMUmBK+aOk4cONbU/lQQw1hYYYPYDHccFBfkwpC5CtHC06+jkjh73EWmNjNcdILcuZiFEpbAnPaAQPGuamrWsZde39FIp/ikTCEEEdKD1dm12yIgp5kcvNiao1iCYLz50sMd/HSI0iM4uZOa8vQcmuXqRefP+1XVuuLQ3Wzk1JVJHqyxCITizqkP/cbCs+RtZiDX0YLO9mPy+WNa/W8xW9xR778TyNaEds2tvFxwMiJWKKDu7wJnkpk4QVeJx4QirTREQYH700rJEf5+eOn63UJoaMjMLuw2zPN+1GYZKzHyU6YNyNMxE3i2LL1l5/nyhmi2A0ByH8AWsmV3GubZm0AD0gxa1yoOFhfx/4XdmwD8LniUKNeXFmIT2z+WCQuEJjv8Ubm021qccOrRFL3mw1+u5Usjm5A7EblcJM9IfKwMPPUVZTOeYeiEBNRc3BAwZ20ARJauS1g9iKZT1syB8lZNfb8RBnQaSjwRmvwaQcofMkO6RGrbGqdx6DTavXuv9i4jQS/abjigTs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
