travis:
  secure:
    BINSTAR_TOKEN: KQFoIGdn3SAepOF4MFJsWJJasYhkyMkiT2lQZdxQUcaRrO/vo0uKPevYp8v6r+2gQSjOtVTPCYFHaKiOUMJQU+hDm6xrjwNjJUr7mMK30ogff2J5OKs/lbpZzthUKsU1pd/AhEeQBKA7NfhVAgi7fUUj8mCCcMh+wqKWhfknjZIuMBYgXMP5gznlrcsQJm0NXN/eWtCABjmmaB9dkZpOLekLV1QMMHkRnwbBHQkxAjckvVV67IrOZzzCJ01+FT/DpEaMgvy/CQPjyLLui7+uWoZprJxNlNU+jhlW3P8dyKNA9TdN7IMQKDsavliKD6Ip93owZaBhdkyQI5D/xrSHzmj1kdYGswHsY3RgtzD809kYgmCZFDCeDQCNr6uvfHo3brjOYVlSZZEMyR1gxNMQzBBWwEJXNo/yu3PvbLOs3oz2ExUCcs9ktdd5QD10sxgtU0utc6hafs3cI8UNM3u7nSqy/P/ueir+Aq1KXhokQL0S4P6krjJh3vBpKjAr52gP9/qdSeAgKeVzqCU4wAXA2gjNMN9KbbYo/bc+Es+VnUsq5Jb1HEYVjZ/Lpt28CqvarrULvThm7nws/ZqOlpJQE3OGxzLJYMaAji3AuLjNJUn7P5MsbApaZIXYJpM3sooDubpZoMd0CxhOal7uJxWi6kd1ygTWRccCpwXyqTHB2Jo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
