travis:
  secure:
    BINSTAR_TOKEN: kEYYe5dgvvy/4ftSRrA1j/aVFjQ9kckb0HwVW7OrVRWvdruc5vArhnwz77hzbv4EQ5JMaFAoCqUvb7B2bVKZsjRYMochtEok/pBxZrX0t5PPqpEIguaIufNfFEMqX/UfSoY0lSM4F9J1TI9Aia81bLHNe4CAD6flA9a0Tt8StexJQCfLLHCGki/Jql/aHzvTN+VL9VgQ1Ikb0Q5Vp2Qcr3H6Dg4z7/ungOw0hSI5SrgDSCwmBM5f8420sokFOHNT+AojYVS/OOzVSb+f7pt1dvUI/zUAAZ3kz62PBSmxhj4HSJLgkoo54Ff6Pq/FA/Ee9vl1c8LgNA9e9R4aa6xdtawcl3CeAnbmGg7SqNj9DOWG2rRh5I7LE1MqX0uxEeqPiNeE9/lxeqnP+h1CTPAJhjGmnO1uO+WxHcnY5FtB3EhBqDEH0CRcVaHKeyelkCbK54Qp1O9q2vWmfAAfKnrPGcIk+HoikJRVj8Bb/AqO23fhASsb6S+0gVfjfkvLo1DfOZRFr3Q8NlrT9OeXlCRZThRUcBbF9TJlCtKkqCLphd2dI1FlvRiM2bF/J54g4iylk1kiJ0YBGj6r5p1BApJtNJYTraL8JoychQiMGe/PguURRzGahJL8ndfw8aDa1tnVLgDx2mzZoGCFsPNSDWj1hVTQrsodEwsUTWPv93mOT9c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
